# Values passed to the dependency chart (falcosecurity/falco)
falco:
  falco:
    jsonOutput: true
    httpOutput:
      enabled: true
      url: "http://falco-sidekick:2801"

  falcosidekick:
    enabled: true
    config:
      debug: true
      webhook:
        address: "https://umt65skc2e.execute-api.us-east-1.amazonaws.com/prod/v1/cwp/events"
        method: POST

# Values used by this wrapper chart
heartbeat:
  enabled: true
  nameSuffix: "heartbeat"
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  startingDeadlineSeconds: 120 # if missed schedule, how long controller will still start it
  activeDeadlineSeconds: 60 # hard kill if it runs too long

  backoffLimit: 1

  image:
    repository: curlimages/curl
    tag: "8.5.0"
    pullPolicy: IfNotPresent

  secretRefName: t12-cwp-secret

  endpoint: "https://7678c2255829.ngrok-free.app"

  # Curl timeouts to avoid stuck Jobs
  curl:
    connectTimeoutSeconds: 20 
    maxTimeSeconds: 60 

  podLabels: {}
  podAnnotations: {}
